[tool.poetry]
name = "lacss"
version = "0.3.1"
description = "Cell segmentation and tracking"
authors = ["Ji Yu <jyu@uchc.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
flax = ">=0.4.1"
tqdm = "^4.65.0"
numpy = ">=1.18.0"
imageio = "^2.9.0"
scikit-image = ">=0.19.0"
cloudpickle = "^2.2.1"

[tool.poetry.group.dev.dependencies]
jax = "0.4.2"
jaxlib = "0.4.1+cuda11.cudnn82"
typer = ">=0.4.0"
tensorflow-cpu = "^2.8.0"
setuptools = "67.4.0"
pycocotools = "^2.0.6"
pytest = "^7.2.2"
jupyterlab = "^3.6.1"
imagecodecs = "^2023.3.16"

[[tool.poetry.source]]
name = "jax"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
default = false
secondary = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
